name: coverage

on:
  push:
    branches: main

jobs:
  check-coverage:
    name: Check code coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # check code coverage, store results and generate badge.
      # coverage.py creates a .gitignore with '*' where it's run; remove it
      # to keep the coverage report and badge
      - name: Coverage
        run: |
          coverage run --source=arksia -m pytest arksia/test/tests.py
          coverage report
          mkdir -p test/coverage
          coverage html -d test/coverage
          rm test/coverage/.gitignore
          coverage-badge -f -o test/coverage/badge.svg
